# Generated by Django 6.0.2 on 2026-03-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('current_weight', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('gender', models.CharField(max_length=1)),
                ('activity_level', models.CharField(max_length=20)),
                ('food_pref', models.CharField(max_length=10)),
                ('cuisine', models.CharField(max_length=50)),
                ('bmi', models.FloatField()),
                ('bmi_category', models.CharField(max_length=20)),
                ('target_calories', models.FloatField()),
                ('tdee', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('breakfast_options', models.JSONField()),
                ('lunch_options', models.JSONField()),
                ('dinner_options', models.JSONField()),
                ('recommendations_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='food_recommendation_system.foodrecommendation')),
            ],
        ),
    ]
