# Generated by Django 6.0.1 on 2026-01-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AI Trainer Membership', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(choices=[('1M', '1 Month'), ('3M', '3 Months'), ('6M', '6 Months'), ('1Y', '1 Year')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('feature_1', models.CharField(max_length=80)),
                ('feature_2', models.CharField(max_length=80)),
                ('feature_3', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
