# Generated by Django 6.0.2 on 2026-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notif_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_rejected', 'Booking Rejected'), ('payment_required', 'Payment Required'), ('workout_plan', 'Workout Plan Update'), ('diet_plan', 'Diet Plan Update'), ('meal_added', 'Meal Added'), ('exercise_added', 'Exercise Added'), ('plan_deleted', 'Plan Deleted'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
