# Generated by Django 5.2.4 on 2026-02-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0014_trainerbooking_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('focus_area', models.CharField(help_text='e.g., Chest & Triceps, Legs, Cardio, Rest', max_length=100)),
                ('is_rest_day', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ClientFitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=1, help_text='Height in cm', max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, help_text='Weight in kg', max_digits=5)),
                ('age', models.PositiveIntegerField()),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintain', 'Maintain Fitness'), ('endurance', 'Improve Endurance'), ('flexibility', 'Improve Flexibility'), ('general', 'General Fitness')], default='general', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (Little or no exercise)'), ('light', 'Lightly Active (1-3 days/week)'), ('moderate', 'Moderately Active (3-5 days/week)'), ('active', 'Very Active (6-7 days/week)'), ('extreme', 'Extremely Active (Athlete)')], default='sedentary', max_length=20)),
                ('diet_preference', models.CharField(choices=[('no_preference', 'No Preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('non_veg', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian'), ('keto', 'Keto')], default='no_preference', max_length=20)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or injuries', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Any food allergies', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profiles', to='trainer.trainerbooking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('daily_calories', models.PositiveIntegerField(blank=True, help_text='Target daily calories', null=True)),
                ('protein_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('fat_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_weeks', models.PositiveIntegerField(default=4, help_text='Plan duration in weeks')),
                ('notes', models.TextField(blank=True, help_text='Additional trainer notes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='trainer.trainerbooking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='trainer.trainerregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], max_length=20)),
                ('title', models.CharField(help_text='e.g., Oatmeal with Fruits', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description/recipe', null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein', models.PositiveIntegerField(blank=True, help_text='Protein in grams', null=True)),
                ('carbs', models.PositiveIntegerField(blank=True, help_text='Carbs in grams', null=True)),
                ('fat', models.PositiveIntegerField(blank=True, help_text='Fat in grams', null=True)),
                ('time', models.CharField(blank=True, help_text='e.g., 7:00 AM', max_length=20, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='fitness_plan.dietplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(help_text='e.g., 12, 8-12, 30 sec', max_length=50)),
                ('rest_seconds', models.PositiveIntegerField(default=60, help_text='Rest time between sets in seconds')),
                ('notes', models.TextField(blank=True, help_text='Form tips, modifications, etc.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness_plan.workoutday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('duration_weeks', models.PositiveIntegerField(default=4, help_text='Plan duration in weeks')),
                ('notes', models.TextField(blank=True, help_text='Additional trainer notes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='trainer.trainerbooking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='trainer.trainerregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='fitness_plan.workoutplan'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('workout_plan', 'day')},
        ),
    ]
