# Generated by Django 5.2.4 on 2026-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional meal photo', null=True, upload_to='meal_images/'),
        ),
    ]
