# Generated by Django 5.2.4 on 2026-03-03 16:03

import fitness_plan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_plan', '0002_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional meal photo', null=True, upload_to=fitness_plan.models.meal_image_upload_path),
        ),
    ]
