# Generated by Django 5.2.4 on 2026-01-30 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=255)),
                ('certification', models.FileField(blank=True, null=True, upload_to='trainer/certifications/')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='trainer/profile_pics/')),
                ('identity_proof', models.FileField(blank=True, null=True, upload_to='trainer/identity_proofs/')),
                ('experience_verification', models.FileField(blank=True, null=True, upload_to='trainer/experience_verifications/')),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
