# Generated by Django 5.2.4 on 2026-01-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerregistration',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='trainerregistration',
            name='experience_verification',
        ),
        migrations.RemoveField(
            model_name='trainerregistration',
            name='identity_proof',
        ),
        migrations.RemoveField(
            model_name='trainerregistration',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='trainerregistration',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrainerRegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('certification', 'Certification'), ('profile_pic', 'Profile Picture'), ('identity_proof', 'Identity Proof'), ('experience_verification', 'Experience Verification')], max_length=40)),
                ('file', models.FileField(upload_to='trainer_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trainer.trainerregistration')),
            ],
        ),
    ]
