# Generated by Django 5.2.4 on 2026-02-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_remove_trainerregistration_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerregistration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
