# Generated by Django 5.2.4 on 2026-02-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_trainerregistration_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerregistration',
            name='available_time',
            field=models.CharField(blank=True, help_text='Available time slots', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainerregistration',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly training price in USD', max_digits=10, null=True),
        ),
    ]
