# Generated by Django 5.2.4 on 2026-02-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_trainerregistration_available_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerregistration',
            name='available_time',
            field=models.TextField(blank=True, help_text='Available time slots', null=True),
        ),
        migrations.AlterField(
            model_name='trainerregistration',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly training price in Rupees', max_digits=10, null=True),
        ),
    ]
