# Generated by Django 5.2.4 on 2026-02-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_alter_trainerregistration_available_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='trainer_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trainer.trainerregistration')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
