# Generated by Django 5.2.4 on 2026-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainernotification',
            name='notif_type',
            field=models.CharField(choices=[('booking', 'New Booking'), ('cancellation', 'Booking Cancelled'), ('approved', 'Registration Approved'), ('rejected', 'Registration Rejected'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
