# Generated by Django 5.2.4 on 2026-02-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_alter_usernotification_notif_type_dietplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermessage',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='trainermessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='trainernotification',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='trainernotification',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainerpayment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='trainerpayment',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainerpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='DietPlan',
        ),
        migrations.DeleteModel(
            name='TrainerMessage',
        ),
        migrations.DeleteModel(
            name='TrainerNotification',
        ),
        migrations.DeleteModel(
            name='TrainerPayment',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
