# Generated by Django 5.2.4 on 2026-02-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_remove_trainermessage_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Booking amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainerbooking',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, help_text='Payment must be made by this date', null=True),
        ),
        migrations.AddField(
            model_name='trainerbooking',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('overdue', 'Payment Overdue')], default='not_required', max_length=20),
        ),
    ]
