# Generated by Django 6.0.2 on 2026-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_trainerbooking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerregistrationdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
