# Generated by Django 6.0.2 on 2026-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_trainerregistrationdocument_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='trainerbooking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('trainer', 'Trainer'), ('user', 'User'), ('system', 'System')], max_length=10, null=True),
        ),
    ]
