# Generated by Django 6.0.2 on 2026-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_alter_trainerbooking_status_trainerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbooking',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Training access valid until this date (inclusive)', null=True),
        ),
    ]
