# Generated by Django 6.0.2 on 2026-04-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_trainerbooking_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerbooking',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Training access valid until this date and time (inclusive)', null=True),
        ),
    ]
