# Generated by Django 6.0.2 on 2026-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_alter_trainerbooking_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbooking',
            name='completion_email_sent',
            field=models.BooleanField(default=False, help_text='Track if thank you/review email has been sent after expiry'),
        ),
        migrations.AddField(
            model_name='trainerbooking',
            name='expiry_warning_sent',
            field=models.BooleanField(default=False, help_text='Track if 3-day expiry warning email has been sent'),
        ),
    ]
