# Generated by Django 6.0.2 on 2026-04-16 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0019_trainerreview_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerregistrationdocument',
            name='file',
            field=models.FileField(upload_to='trainer_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
