# Generated by Django 6.0.2 on 2026-02-16 11:41

import login_logout_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout_register', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=login_logout_register.models.profile_picture_path),
        ),
    ]
