# Generated by Django 6.0.2 on 2026-03-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout_register', '0005_homebanner_premiumservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeBanner',
        ),
        migrations.DeleteModel(
            name='PremiumService',
        ),
    ]
