# Generated by Django 5.2.4 on 2026-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membershipplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
