# Generated by Django 6.0.2 on 2026-02-05 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0004_alter_membershipplan_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(db_index=True, max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('purchase_order_id', models.CharField(max_length=255, unique=True)),
                ('purchase_order_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(help_text='Amount in paisa')),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Expired', 'Expired'), ('User canceled', 'User canceled'), ('Refunded', 'Refunded'), ('Partially refunded', 'Partially refunded')], default='Initiated', max_length=30)),
                ('refunded', models.BooleanField(default=False)),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('membership_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payment_kha_user_id_d4f436_idx'), models.Index(fields=['pidx'], name='payment_kha_pidx_f74200_idx'), models.Index(fields=['transaction_id'], name='payment_kha_transac_17aea1_idx')],
            },
        ),
    ]
