# Generated by Django 6.0.2 on 2026-02-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_usermembership'),
        ('payment', '0001_initial'),
        ('trainer', '0014_trainerbooking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaltipayment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.trainerbooking'),
        ),
        migrations.AddField(
            model_name='khaltipayment',
            name='payment_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('booking', 'Trainer Booking')], default='membership', max_length=20),
        ),
        migrations.AlterField(
            model_name='khaltipayment',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershipplan'),
        ),
    ]
