# Generated by Django 6.0.2 on 2026-03-04 07:56

import django.db.models.deletion
import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_khaltipayment_booking_khaltipayment_payment_type_and_more'),
        ('trainer', '0014_trainerbooking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Booking amount minus 10% platform fee', max_digits=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_qr', models.ImageField(blank=True, null=True, upload_to=payment.models.qr_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='trainer.trainerbooking')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='trainer.trainerregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
