# Generated by Django 6.0.2 on 2026-03-04 08:07

import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_trainerpaymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpaymentrequest',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Admin uploads payment receipt after transfer', null=True, upload_to=payment.models.receipt_upload_path),
        ),
    ]
