# Generated by Django 6.0.2 on 2026-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('system', 'System'), ('cancellation', 'Cancellation')], default='normal', max_length=20),
        ),
    ]
